version: '3.7'

services:
  web:
    image: nginx:1.16.1
    ports:
      - "58002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html